/**
 * 作物マスター — 栽培暦・作物ガイド（R08/R09 / WBS 3.1・4.19）
 *
 * 「今月の菜園仕事」（3.2）・作物ガイド（3.3）・「次の作業」（3.4）・進行帯の元データ。
 * サンプルシード（seed.ts）とは別物で、**本番ビルドにも常に投入される**。
 *
 * 執筆の決め:
 * - 地域帯は寒冷地・中間地・暖地の 3 区分（§9）。中間地を基準に書き、
 *   寒冷地は春秋を約 1 か月内側へ、暖地は秋冬を約 1 か月外側へずらす
 * - 月単位。旬・上旬の粒度は持たない — 家庭菜園の判断は月で足りる
 * - 年またぎは startMonth > endMonth で表す（10 月〜翌 2 月 = 10, 2）
 * - 同じ kind に春秋 2 つの窓を持てる（例: ジャガイモ）。窓は最大 2 つ
 * - 一般的な露地・プランター栽培の目安。品種や年ごとの気候では前後する
 *   （利用規約の免責どおり「目安」であり、正確性はレビューで担保する）
 * - **列は 4.19 第 1 段で決め切った**（docs/検討-作物マスター100品目.md §3-1）。
 *   あとから列を足すと全品目を触り直すことになる
 * - 出典を伴う値（guide）と、出典なしの編集者判断（editorial）を分けて持つ。
 *   editorial は一覧の絞り込みと登録時の助言にだけ使い、暦や「次の作業」の判定には使わない
 * - id は新規から**和名のヘボン式ローマ字**で統一する（`crop-rukkora`）。既存の英語 id
 *   （`crop-cucumber`）は plantings.crop_id に保存済みなので変えない
 *
 * ここを変えたら CROP_MASTER_VERSION を上げること。据え置くと
 * 投入済みの端末が同期をスキップし、新しい行が入らない。
 */
import type { Region } from '../services/region.service';

// v2: 春夏 18 作物を追加して 30 作物に（3.1b 後半）
// v3: 公的資料と突き合わせて補正（寒冷地を JA 北海道の実期に合わせ 1〜2 か月前倒し、
//     暖地ジャガイモ秋作の植付を 8〜9 月に）。出典は CROP_MASTER_REFERENCES
// v4: 4.19 第 1 段。20 品目を足して 50 品目に。全品目に分類・出典・水やり間隔・発芽日数・
//     定植日数・追肥間隔・収穫の幅と期間・適温・連作年数・作業・多年草・編集者判断を追加（#180）
export const CROP_MASTER_VERSION = 4;

export type CropCalendarKind = 'sow' | 'plant' | 'harvest';

export interface CropCalendarWindow {
  region: Region;
  kind: CropCalendarKind;
  /** 1〜12 */
  startMonth: number;
  /** 1〜12。startMonth より小さければ年またぎ */
  endMonth: number;
}

/** 一覧のセクションと検索の絞り込み。表示順は CROP_CATEGORY_ORDER */
export type CropCategory =
  | 'leaf'
  | 'root'
  | 'fruit'
  | 'bean'
  | 'tuber'
  | 'allium'
  | 'herb'
  | 'tree';

export const CROP_CATEGORY_ORDER: readonly CropCategory[] = [
  'leaf',
  'root',
  'fruit',
  'bean',
  'tuber',
  'allium',
  'herb',
  'tree',
] as const;

export const CROP_CATEGORY_LABEL: Record<CropCategory, string> = {
  leaf: '葉もの',
  root: '根もの',
  fruit: '実もの',
  bean: '豆',
  tuber: 'いも',
  allium: 'ネギ類',
  herb: 'ハーブ',
  tree: '果樹・多年草',
};

/**
 * 作物ごとの作業。「次の作業」を収穫と追肥の 2 種類から広げる（R10）。
 * 記録は作業ログの剪定（摘芯・芽かき・摘果）か その他（支柱・土寄せ・間引き・ネット）に落とす。
 */
export type CropTaskKind = 'pinch' | 'stake' | 'hill' | 'thin' | 'sucker' | 'fruit-thin' | 'net';

export const CROP_TASK_LABEL: Record<CropTaskKind, string> = {
  pinch: '摘芯',
  stake: '支柱立て',
  hill: '土寄せ',
  thin: '間引き',
  sucker: '芽かき',
  'fruit-thin': '摘果',
  net: '防虫ネット',
};

export interface CropTask {
  kind: CropTaskKind;
  /** 植え付け（または種まき）からの日数 */
  afterDays: number;
  /** 一言（「本葉 5〜6 枚で」など）。無ければラベルだけ出す */
  note?: string;
}

/** 出典と突き合わせる値。県指針・種袋の裏に載る範囲だけ */
export interface CropGuideMaster {
  /** 株間の目安（cm） */
  spacingCm: number;
  /** full=日なた / partial=半日陰 */
  sunlight: 'full' | 'partial';
  wateringNote: string;
  /** 水やりの目安間隔（日）。R26 ケアスケジュール自動提案の既定値。雨まかせなら null */
  wateringIntervalDays: number | null;
  /** 発芽までの日数。苗から始める作物は null */
  germinationDays: number | null;
  /** 種まきから定植までの日数（苗物だけ）。R33 定植適期の材料 */
  transplantAfterDays: number | null;
  /** 植え付け（または種まき）から初回の追肥までの日数。R10 の判定に使う */
  fertilizeAfterDays: number | null;
  /** 2 回目以降の追肥間隔（日）。1 回で済む作物は null */
  fertilizeIntervalDays: number | null;
  /** 植え付け（または種まき）から収穫までの日数。R10 の判定に使う。多年草は null */
  harvestAfterDays: number | null;
  /** 収穫の幅（最短〜最長）。進行帯に「窓」を描く。多年草は null */
  harvestWindowDays: { min: number; max: number } | null;
  /** 初収穫から採り続けられる日数。一度で採り切る作物は null */
  harvestDurationDays: number | null;
  /** 発芽適温・生育適温（℃）。WBS 4.13 の天気連携と R33 が使う */
  temperature: { germination: [number, number]; growth: [number, number] } | null;
  /** 連作を避ける年数。0 = 連作障害が出にくい。R17 は科だけでは足りない */
  rotationYears: number | null;
  /** 作物ごとの作業（摘芯・支柱・土寄せ…）。日数順 */
  tasks: CropTask[];
  /** 気をつける虫・病気 */
  commonPests: string[];
  tips: string;
}

/** 出典なしの判断。一覧の絞り込みと登録時の助言にだけ使い、暦や次の作業の判定には使わない */
export interface CropEditorial {
  /** 初心者向けか */
  beginner: boolean;
  /** プランターで育つか。育つなら必要な深さ（cm） */
  container: { ok: true; depthCm: number } | { ok: false };
}

export interface CropMaster {
  id: string;
  name: string;
  /** ひらがな。検索の読み仮名 */
  nameReading: string;
  /** 科。R17 連作障害チェックの判定キー */
  family: string;
  category: CropCategory;
  /** 収穫の既定単位（HARVEST_UNITS の語彙） */
  defaultUnit: 'piece' | 'g' | 'kg' | 'bunch' | 'plant';
  /** 多年草。収穫日数を持たず、ガイドに「翌年から収穫」と出す */
  perennial?: true;
  /** CROP_MASTER_REFERENCES の id。1 つ以上 */
  sourceIds: string[];
  calendars: CropCalendarWindow[];
  guide: CropGuideMaster;
  editorial: CropEditorial;
}

export interface CropReference {
  id: string;
  name: string;
  url: string;
}

/**
 * 栽培暦・ガイドの出典（R08/R09）。
 *
 * 内容は下記の公開資料を参考に、家庭菜園向けの「月単位の目安」として
 * 独自にまとめ直したもの（表の転載ではない）。アプリ内では
 * 「今月の菜園仕事」カードと作物ガイドに小さく出典として表示する。
 * 作物ごとの対応は各作物の `sourceIds`。検証の記録は docs/栽培暦の出典.md。
 *
 * 公的資料（農水省・県・JA）を優先し、ハーブ・果樹で足りない分だけ
 * 種苗会社の公開資料を許す（決定③・2026-09-05）。
 */
export const CROP_MASTER_REFERENCES: readonly CropReference[] = [
  {
    id: 'maff-sehi',
    name: '農林水産省「都道府県の施肥基準・野菜栽培技術指針」',
    url: 'https://www.maff.go.jp/j/seisan/kankyo/hozen_type/h_sehi_kizyun/',
  },
  {
    id: 'maff-akita-konsai',
    name: '秋田県「野菜栽培技術指針 根菜類」（農林水産省収載）',
    url: 'https://www.maff.go.jp/j/seisan/kankyo/hozen_type/h_sehi_kizyun/attach/pdf/aki3-7.pdf',
  },
  {
    id: 'ja-hokkaido',
    name: 'JAグループ北海道「チャレンジ！家庭菜園 主要野菜のは種・定植・収穫時期」',
    url: 'https://ja-dosanko.jp/agriculture/charenge/no7/',
  },
  {
    id: 'nagasaki-potato',
    name: '長崎県農林技術開発センター「バレイショ栽培マニュアル」',
    url: 'https://www.pref.nagasaki.jp/e-nourin/nougi/manual/kogane2018.pdf',
  },
  {
    id: 'maff-potato',
    name: '農林水産省 消費者相談「国内のジャガイモの栽培時期」',
    url: 'https://www.maff.go.jp/j/heya/sodan/1204/01a.html',
  },
  {
    id: 'nagano-kasai-ondo',
    name: '長野県「主な果菜類の発芽適温と育苗温度のめやす」',
    url: 'https://www.pref.nagano.lg.jp/sakuchi/nosei-aec/joho/gijutsu/documents/kasai-ondo.pdf',
  },
  {
    id: 'okinawa-tokusai',
    name: '沖縄県「特別栽培農産物 栽培マニュアル」',
    url: 'https://www.pref.okinawa.jp/shigoto/nogyo/1010362/1010676/1010680.html',
  },
  {
    id: 'saitama-satoimo',
    name: '埼玉県農業技術研究センター「水田におけるサトイモ栽培マニュアル」',
    url: 'https://www.pref.saitama.lg.jp/documents/104573/manyuaru.pdf',
  },
  {
    id: 'saitama-shoga',
    name: '埼玉県農業技術研究センター「ショウガの栽培マニュアル」',
    url: 'https://www.pref.saitama.lg.jp/documents/103704/syougamanyuaru.pdf',
  },
  {
    id: 'chiba-rakkasei',
    name: '千葉県「落花生栽培の手引」',
    url: 'https://www.pref.chiba.lg.jp/ninaite/seikafukyu/documents/05_rakkasei-tebiki.pdf',
  },
  {
    id: 'kochi-paseri',
    name: 'こうち農業ネット（高知県）「家庭菜園（パセリ）」',
    url: 'https://www.nogyo.tosa.pref.kochi.lg.jp/info/dtl.php?ID=590',
  },
  {
    id: 'jeinou-calendar',
    name: 'みんなの農業広場「栽培カレンダー」（全国農業改良普及支援協会）',
    url: 'https://www.jeinou.com/benri/garden/planting_list.html',
  },
  {
    id: 'jeinou-satoimo',
    name: 'みんなの農業広場「サトイモの作り方（家庭菜園向け）」',
    url: 'https://www.jeinou.com/benri/garden/root/2009/09/301000.html',
  },
  {
    id: 'jeinou-myoga',
    name: 'みんなの農業広場「ミョウガ（花ミョウガ）の作り方（家庭菜園向け）」',
    url: 'https://www.jeinou.com/benri/garden/leaf_stem_vegetables/2012/04/250935.html',
  },
  {
    id: 'ja-kiso-kushinsai',
    name: 'JA木曽「家庭菜園アドバイス 空芯菜（エンサイ）の栽培」',
    url: 'https://www.ja-kiso.iijan.or.jp/memo/1066',
  },
  {
    id: 'ja-kiso-papurika',
    name: 'JA木曽「家庭菜園アドバイス ピーマン、パプリカの栽培について」',
    url: 'https://www.ja-kiso.iijan.or.jp/memo/1223',
  },
  {
    id: 'ja-hareoka-rukkora',
    name: 'JA晴れの国岡山「家庭菜園 ルッコラ」',
    url: 'https://www.ja-hareoka.or.jp/agri_food/kateisaien/2022/029/',
  },
  {
    id: 'ja-hareoka-sanchu',
    name: 'JA晴れの国岡山「家庭菜園 サンチュ」',
    url: 'https://www.ja-hareoka.or.jp/agri_food/kateisaien/2025/058/',
  },
  {
    id: 'ja-nishikasugai-moroheiya',
    name: 'JA西春日井「家庭菜園 モロヘイヤ」',
    url: 'https://www.ja-nishikasugai.com/2_data/moroheiya',
  },
  {
    id: 'ja-nishikasugai-shishito',
    name: 'JA西春日井「家庭菜園 シシトウ」',
    url: 'https://www.ja-nishikasugai.com/garden_vegetable/9254/',
  },
  {
    id: 'ja-saitama-nira',
    name: 'JAさいたま「ニラは春先の株分け更新が大切」',
    url: 'https://www.ja-saitama.or.jp/wp/?p=271',
  },
  {
    id: 'takii-manual',
    name: 'タキイ種苗「家庭菜園 野菜栽培マニュアル」（種苗会社の公開資料）',
    url: 'https://www.takii.co.jp/tsk/manual/',
  },
] as const;

/** アプリ内に小さく出す 1 行（カード・ガイドの脚注） */
export const CROP_MASTER_ATTRIBUTION = '農林水産省・JAグループ等の公開資料をもとにした目安です';

/** 作物の sourceIds を出典の行に引き直す。順序は CROP_MASTER_REFERENCES のまま */
export function referencesFor(sourceIds: readonly string[]): CropReference[] {
  const wanted = new Set(sourceIds);
  return CROP_MASTER_REFERENCES.filter((ref) => wanted.has(ref.id));
}

/** id でマスターを引く（ガイド画面の出典など、DB に持たない値のため） */
export function findCropMaster(cropId: string): CropMaster | undefined {
  return CROP_MASTER.find((crop) => crop.id === cropId);
}

// 短縮のためのヘルパ。値の意味は CropGuideMaster / CropEditorial を見る
const NO_CONTAINER = { ok: false } as const;
const container = (depthCm: number) => ({ ok: true, depthCm }) as const;
const window = (min: number, max: number) => ({ min, max });
const temp = (
  germination: [number, number],
  growth: [number, number],
): CropGuideMaster['temperature'] => ({ germination, growth });

/**
 * 50 品目（WBS 3.1 → 4.19 第 1 段）。秋冬 12 + 春夏 18 + 第 1 段 20。
 * 秋冬を先に書いたのは、v1.0 公開（10 月）時点で「今月の仕事」に
 * 実データが載るようにするため。
 */
export const CROP_MASTER: CropMaster[] = [
  {
    id: 'crop-daikon',
    name: 'ダイコン',
    nameReading: 'だいこん',
    family: 'アブラナ科',
    category: 'root',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'maff-akita-konsai'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 8 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 8, endMonth: 9 },
      { region: 'temperate', kind: 'harvest', startMonth: 10, endMonth: 12 },
      { region: 'warm', kind: 'sow', startMonth: 9, endMonth: 10 },
      { region: 'warm', kind: 'harvest', startMonth: 11, endMonth: 1 },
    ],
    guide: {
      spacingCm: 25,
      sunlight: 'full',
      wateringNote: '発芽まで乾かさない。根が育ちはじめたら控えめでよい。',
      wateringIntervalDays: 3,
      germinationDays: 4,
      transplantAfterDays: null,
      fertilizeAfterDays: 30,
      fertilizeIntervalDays: null,
      harvestAfterDays: 60,
      harvestWindowDays: window(55, 75),
      harvestDurationDays: null,
      temperature: temp([15, 30], [17, 20]),
      rotationYears: 1,
      tasks: [
        { kind: 'thin', afterDays: 10, note: '本葉 1 枚で 1 か所 2 本に' },
        { kind: 'thin', afterDays: 25, note: '本葉 5〜6 枚で 1 本に' },
      ],
      commonPests: ['アブラムシ', 'キスジノミハムシ', 'ヨトウムシ'],
      tips: '深く耕して石を取りのぞくと又根になりにくい。間引きは本葉 1 枚と 5〜6 枚のころの 2 回。',
    },
    editorial: { beginner: true, container: container(30) },
  },
  {
    id: 'crop-kabu',
    name: 'カブ',
    nameReading: 'かぶ',
    family: 'アブラナ科',
    category: 'root',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'maff-akita-konsai'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 8 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 8, endMonth: 10 },
      { region: 'temperate', kind: 'harvest', startMonth: 10, endMonth: 12 },
      { region: 'warm', kind: 'sow', startMonth: 9, endMonth: 10 },
      { region: 'warm', kind: 'harvest', startMonth: 11, endMonth: 1 },
    ],
    guide: {
      spacingCm: 10,
      sunlight: 'full',
      wateringNote: '乾き続けると実が割れる。土の表面が乾いたらたっぷり。',
      wateringIntervalDays: 2,
      germinationDays: 4,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: null,
      harvestAfterDays: 45,
      harvestWindowDays: window(40, 60),
      harvestDurationDays: null,
      temperature: temp([20, 25], [15, 20]),
      rotationYears: 1,
      tasks: [
        { kind: 'thin', afterDays: 10, note: '本葉 1〜2 枚で' },
        { kind: 'thin', afterDays: 20, note: '本葉 4〜5 枚で株間 10cm に' },
      ],
      commonPests: ['アブラムシ', 'キスジノミハムシ'],
      tips: '小カブは密植でよく、間引き菜も食べられる。取り遅れると実が割れるので早めに収穫する。',
    },
    editorial: { beginner: true, container: container(20) },
  },
  {
    id: 'crop-ninjin',
    name: 'ニンジン',
    nameReading: 'にんじん',
    family: 'セリ科',
    category: 'root',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'maff-akita-konsai', 'okinawa-tokusai'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 8, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 7, endMonth: 8 },
      { region: 'temperate', kind: 'harvest', startMonth: 11, endMonth: 1 },
      { region: 'warm', kind: 'sow', startMonth: 8, endMonth: 9 },
      { region: 'warm', kind: 'harvest', startMonth: 12, endMonth: 3 },
    ],
    guide: {
      spacingCm: 10,
      sunlight: 'full',
      wateringNote: '発芽が勝負。芽が出るまで 1 週間ほど毎日欠かさず湿らせる。',
      wateringIntervalDays: 2,
      germinationDays: 10,
      transplantAfterDays: null,
      fertilizeAfterDays: 40,
      fertilizeIntervalDays: 30,
      harvestAfterDays: 110,
      harvestWindowDays: window(100, 130),
      harvestDurationDays: null,
      temperature: temp([15, 25], [18, 21]),
      rotationYears: 1,
      tasks: [
        { kind: 'thin', afterDays: 20, note: '本葉 2〜3 枚で 3cm 間隔に' },
        { kind: 'thin', afterDays: 40, note: '本葉 5〜6 枚で 10cm 間隔に。土寄せも' },
      ],
      commonPests: ['キアゲハの幼虫', 'アブラムシ'],
      tips: '好光性なので土は薄くかける。発芽さえすれば半分成功と言われる。',
    },
    editorial: { beginner: false, container: container(25) },
  },
  {
    id: 'crop-hourensou',
    name: 'ホウレンソウ',
    nameReading: 'ほうれんそう',
    family: 'ヒユ科',
    category: 'leaf',
    defaultUnit: 'bunch',
    sourceIds: ['maff-sehi', 'ja-hokkaido'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 8 },
      { region: 'cold', kind: 'harvest', startMonth: 6, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'harvest', startMonth: 11, endMonth: 1 },
      { region: 'warm', kind: 'sow', startMonth: 10, endMonth: 11 },
      { region: 'warm', kind: 'harvest', startMonth: 12, endMonth: 2 },
    ],
    guide: {
      spacingCm: 5,
      sunlight: 'full',
      wateringNote: '表面が乾いたらたっぷり。過湿は根腐れのもと。',
      wateringIntervalDays: 3,
      germinationDays: 7,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: null,
      harvestAfterDays: 40,
      harvestWindowDays: window(30, 50),
      harvestDurationDays: null,
      temperature: temp([15, 20], [15, 20]),
      rotationYears: 1,
      tasks: [{ kind: 'thin', afterDays: 14, note: '本葉 2〜3 枚で 5cm 間隔に' }],
      commonPests: ['アブラムシ', 'ヨトウムシ'],
      tips: '酸性の土が苦手。植え付け前に苦土石灰をよく混ぜる。寒さに当たると甘くなる。',
    },
    editorial: { beginner: false, container: container(15) },
  },
  {
    id: 'crop-komatsuna',
    name: 'コマツナ',
    nameReading: 'こまつな',
    family: 'アブラナ科',
    category: 'leaf',
    defaultUnit: 'bunch',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'okinawa-tokusai'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 8 },
      { region: 'cold', kind: 'harvest', startMonth: 6, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'harvest', startMonth: 10, endMonth: 12 },
      { region: 'warm', kind: 'sow', startMonth: 9, endMonth: 11 },
      { region: 'warm', kind: 'harvest', startMonth: 10, endMonth: 1 },
    ],
    guide: {
      spacingCm: 5,
      sunlight: 'full',
      wateringNote: '表面が乾いたらたっぷり。プランターでも育てやすい。',
      wateringIntervalDays: 2,
      germinationDays: 3,
      transplantAfterDays: null,
      fertilizeAfterDays: 15,
      fertilizeIntervalDays: null,
      harvestAfterDays: 35,
      harvestWindowDays: window(30, 45),
      harvestDurationDays: null,
      temperature: temp([20, 30], [15, 25]),
      rotationYears: 1,
      tasks: [
        { kind: 'net', afterDays: 1, note: '種まき直後にかける' },
        { kind: 'thin', afterDays: 10, note: '本葉 2 枚で 5cm 間隔に' },
      ],
      commonPests: ['アブラムシ', 'コナガ', 'カブラハバチ'],
      tips: '種まきから 1 か月あまりで収穫できる初心者向け。防虫ネットをかけると虫害がぐっと減る。',
    },
    editorial: { beginner: true, container: container(15) },
  },
  {
    id: 'crop-shungiku',
    name: 'シュンギク',
    nameReading: 'しゅんぎく',
    family: 'キク科',
    category: 'leaf',
    defaultUnit: 'bunch',
    sourceIds: ['maff-sehi', 'ja-hokkaido'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 8 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'harvest', startMonth: 10, endMonth: 12 },
      { region: 'warm', kind: 'sow', startMonth: 9, endMonth: 10 },
      { region: 'warm', kind: 'harvest', startMonth: 11, endMonth: 2 },
    ],
    guide: {
      spacingCm: 10,
      sunlight: 'partial',
      wateringNote: '乾燥に弱い。表面が乾いたらたっぷり。',
      wateringIntervalDays: 2,
      germinationDays: 7,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 40,
      harvestWindowDays: window(35, 60),
      harvestDurationDays: 45,
      temperature: temp([15, 20], [15, 20]),
      rotationYears: 1,
      tasks: [
        { kind: 'thin', afterDays: 14, note: '本葉 2〜3 枚で 10cm 間隔に' },
        { kind: 'pinch', afterDays: 35, note: '草丈 20cm で摘み取り収穫を始める' },
      ],
      commonPests: ['アブラムシ', 'ハモグリバエ'],
      tips: '摘み取り収穫にすると脇芽が伸びて長く楽しめる。香りが強く虫が付きにくい。',
    },
    editorial: { beginner: true, container: container(15) },
  },
  {
    id: 'crop-mizuna',
    name: 'ミズナ',
    nameReading: 'みずな',
    family: 'アブラナ科',
    category: 'leaf',
    defaultUnit: 'plant',
    sourceIds: ['maff-sehi', 'ja-hokkaido'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 8 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'harvest', startMonth: 11, endMonth: 1 },
      { region: 'warm', kind: 'sow', startMonth: 9, endMonth: 11 },
      { region: 'warm', kind: 'harvest', startMonth: 11, endMonth: 2 },
    ],
    guide: {
      spacingCm: 15,
      sunlight: 'full',
      wateringNote: '水切れすると葉が固くなる。名前のとおり水を好む。',
      wateringIntervalDays: 2,
      germinationDays: 4,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: null,
      harvestAfterDays: 40,
      harvestWindowDays: window(30, 50),
      harvestDurationDays: null,
      temperature: temp([20, 25], [15, 25]),
      rotationYears: 1,
      tasks: [
        { kind: 'net', afterDays: 1, note: '種まき直後にかける' },
        { kind: 'thin', afterDays: 12, note: '本葉 2〜3 枚で' },
      ],
      commonPests: ['アブラムシ', 'コナガ'],
      tips: '小株どりなら密植で 30 日、大株どりなら株間を広く。サラダには小株が柔らかい。',
    },
    editorial: { beginner: true, container: container(15) },
  },
  {
    id: 'crop-hakusai',
    name: 'ハクサイ',
    nameReading: 'はくさい',
    family: 'アブラナ科',
    category: 'leaf',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 7 },
      { region: 'cold', kind: 'plant', startMonth: 6, endMonth: 8 },
      { region: 'cold', kind: 'harvest', startMonth: 8, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 8, endMonth: 8 },
      { region: 'temperate', kind: 'plant', startMonth: 8, endMonth: 9 },
      { region: 'temperate', kind: 'harvest', startMonth: 11, endMonth: 1 },
      { region: 'warm', kind: 'sow', startMonth: 8, endMonth: 9 },
      { region: 'warm', kind: 'plant', startMonth: 9, endMonth: 9 },
      { region: 'warm', kind: 'harvest', startMonth: 12, endMonth: 2 },
    ],
    guide: {
      spacingCm: 40,
      sunlight: 'full',
      wateringNote: '結球が始まるまでは乾かさない。始まったら控えめに。',
      wateringIntervalDays: 3,
      germinationDays: 4,
      transplantAfterDays: 20,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 75,
      harvestWindowDays: window(70, 90),
      harvestDurationDays: null,
      temperature: temp([20, 25], [15, 20]),
      rotationYears: 2,
      tasks: [
        { kind: 'net', afterDays: 1, note: '植え付けと同時にかける' },
        { kind: 'hill', afterDays: 20, note: '追肥と一緒に' },
      ],
      commonPests: ['アブラムシ', 'コナガ', 'ヨトウムシ'],
      tips: '植え付けが遅れると結球しない。適期を守るのがいちばんのコツ。防虫ネットは必須級。',
    },
    editorial: { beginner: false, container: NO_CONTAINER },
  },
  {
    id: 'crop-kyabetsu',
    name: 'キャベツ',
    nameReading: 'きゃべつ',
    family: 'アブラナ科',
    category: 'leaf',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'takii-manual'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 7 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'temperate', kind: 'plant', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'harvest', startMonth: 12, endMonth: 3 },
      { region: 'warm', kind: 'plant', startMonth: 10, endMonth: 11 },
      { region: 'warm', kind: 'harvest', startMonth: 3, endMonth: 5 },
    ],
    guide: {
      spacingCm: 40,
      sunlight: 'full',
      wateringNote: '植え付け直後はたっぷり。以後は表面が乾いたら。',
      wateringIntervalDays: 3,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 90,
      harvestWindowDays: window(80, 110),
      harvestDurationDays: null,
      temperature: temp([15, 30], [15, 20]),
      rotationYears: 2,
      tasks: [
        { kind: 'net', afterDays: 1, note: '植え付けと同時にかける' },
        { kind: 'hill', afterDays: 20, note: '追肥と一緒に' },
      ],
      commonPests: ['アオムシ', 'コナガ', 'ヨトウムシ'],
      tips: 'モンシロチョウの幼虫（アオムシ）が大敵。植え付けと同時に防虫ネットをかける。',
    },
    editorial: { beginner: false, container: container(25) },
  },
  {
    id: 'crop-burokkori',
    name: 'ブロッコリー',
    nameReading: 'ぶろっこりー',
    family: 'アブラナ科',
    category: 'leaf',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'takii-manual'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 7 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'temperate', kind: 'plant', startMonth: 8, endMonth: 9 },
      { region: 'temperate', kind: 'harvest', startMonth: 11, endMonth: 2 },
      { region: 'warm', kind: 'plant', startMonth: 9, endMonth: 10 },
      { region: 'warm', kind: 'harvest', startMonth: 12, endMonth: 3 },
    ],
    guide: {
      spacingCm: 40,
      sunlight: 'full',
      wateringNote: '乾燥が続くときはたっぷり。特に植え付け後 2 週間。',
      wateringIntervalDays: 3,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 90,
      harvestWindowDays: window(80, 100),
      harvestDurationDays: 30,
      temperature: temp([20, 25], [15, 20]),
      rotationYears: 2,
      tasks: [
        { kind: 'net', afterDays: 1, note: '植え付けと同時にかける' },
        { kind: 'hill', afterDays: 20, note: '追肥と一緒に。倒れやすい' },
      ],
      commonPests: ['アオムシ', 'コナガ', 'アブラムシ'],
      tips: '頂花蕾を採ったあとも側花蕾が次々出る。硬貨大のうちに追肥すると側花蕾が太る。',
    },
    editorial: { beginner: false, container: container(25) },
  },
  {
    id: 'crop-tamanegi',
    name: 'タマネギ',
    nameReading: 'たまねぎ',
    family: 'ヒガンバナ科',
    category: 'allium',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'takii-manual'],
    calendars: [
      // 寒冷地（北海道など）は春植え・夏どりが主流
      { region: 'cold', kind: 'sow', startMonth: 3, endMonth: 3 },
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 5 },
      { region: 'cold', kind: 'harvest', startMonth: 8, endMonth: 9 },
      { region: 'temperate', kind: 'sow', startMonth: 9, endMonth: 9 },
      { region: 'temperate', kind: 'plant', startMonth: 11, endMonth: 11 },
      { region: 'temperate', kind: 'harvest', startMonth: 5, endMonth: 6 },
      { region: 'warm', kind: 'sow', startMonth: 9, endMonth: 10 },
      { region: 'warm', kind: 'plant', startMonth: 11, endMonth: 12 },
      { region: 'warm', kind: 'harvest', startMonth: 4, endMonth: 6 },
    ],
    guide: {
      spacingCm: 12,
      sunlight: 'full',
      wateringNote: '植え付け後と冬明けの生育期に乾いたら。冬の間は控えめ。',
      wateringIntervalDays: 5,
      germinationDays: 7,
      transplantAfterDays: 55,
      fertilizeAfterDays: 90,
      fertilizeIntervalDays: 30,
      harvestAfterDays: 240,
      harvestWindowDays: window(220, 260),
      harvestDurationDays: null,
      temperature: temp([15, 25], [15, 20]),
      rotationYears: 0,
      tasks: [],
      commonPests: ['アブラムシ', 'ベと病'],
      tips: '苗の太さは鉛筆の半分ほどが適。太すぎるととう立ちする。葉が倒れたら収穫の合図。',
    },
    editorial: { beginner: false, container: container(20) },
  },
  {
    id: 'crop-ninniku',
    name: 'ニンニク',
    nameReading: 'にんにく',
    family: 'ヒガンバナ科',
    category: 'allium',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 9, endMonth: 9 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 7 },
      { region: 'temperate', kind: 'plant', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'harvest', startMonth: 5, endMonth: 6 },
      { region: 'warm', kind: 'plant', startMonth: 10, endMonth: 10 },
      { region: 'warm', kind: 'harvest', startMonth: 4, endMonth: 5 },
    ],
    guide: {
      spacingCm: 15,
      sunlight: 'full',
      wateringNote: '植え付け後にたっぷり。以後は雨まかせでよいが、極端に乾く冬は少し。',
      wateringIntervalDays: null,
      germinationDays: 20,
      transplantAfterDays: null,
      fertilizeAfterDays: 120,
      fertilizeIntervalDays: 45,
      harvestAfterDays: 240,
      harvestWindowDays: window(230, 260),
      harvestDurationDays: null,
      temperature: temp([15, 20], [15, 20]),
      rotationYears: 0,
      tasks: [{ kind: 'sucker', afterDays: 45, note: '芽が 2 本出たら細い方をかく' }],
      commonPests: ['アブラムシ', 'さび病'],
      tips: '大きい鱗片を選んで植えると玉も大きくなる。春に伸びる花芽（ニンニクの芽）も食べられる。',
    },
    editorial: { beginner: true, container: container(20) },
  },
  // ─── 春夏作物（3.1b 後半・v2）────────────────────────────────────────────
  // crop-tomato / crop-cucumber / crop-basil は開発用サンプル(seed.ts)と同じ id。
  // マスターが upsert で正となり、サンプルの暦・ガイドは同期時に置き換わる。
  {
    id: 'crop-tomato',
    name: 'トマト',
    nameReading: 'とまと',
    family: 'ナス科',
    category: 'fruit',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'nagano-kasai-ondo', 'okinawa-tokusai'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'temperate', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'temperate', kind: 'harvest', startMonth: 6, endMonth: 9 },
      { region: 'warm', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 6, endMonth: 10 },
    ],
    guide: {
      spacingCm: 45,
      sunlight: 'full',
      wateringNote: '乾かし気味に育てると甘くなる。実がつき始めたら定期的に。',
      wateringIntervalDays: 3,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 60,
      harvestWindowDays: window(50, 70),
      harvestDurationDays: 90,
      temperature: temp([25, 30], [20, 25]),
      rotationYears: 4,
      tasks: [
        { kind: 'stake', afterDays: 1, note: '植え付けと同時に立てる' },
        { kind: 'sucker', afterDays: 10, note: '以後 1 週間おきに脇芽をかく' },
        { kind: 'pinch', afterDays: 60, note: '支柱の高さで芯を止める' },
      ],
      commonPests: ['アブラムシ', 'オオタバコガ', '尻腐れ（カルシウム不足）'],
      tips: '脇芽かきをこまめに。支柱は植え付けと同時に立てる。ミニトマトは初心者向け。',
    },
    editorial: { beginner: true, container: container(30) },
  },
  {
    id: 'crop-cucumber',
    name: 'キュウリ',
    nameReading: 'きゅうり',
    family: 'ウリ科',
    category: 'fruit',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'nagano-kasai-ondo', 'okinawa-tokusai'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'temperate', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'temperate', kind: 'harvest', startMonth: 6, endMonth: 9 },
      { region: 'warm', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 5, endMonth: 10 },
    ],
    guide: {
      spacingCm: 45,
      sunlight: 'full',
      wateringNote: '実のほとんどが水分。夏は毎朝たっぷり、水切れさせない。',
      wateringIntervalDays: 1,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 15,
      fertilizeIntervalDays: 15,
      harvestAfterDays: 40,
      harvestWindowDays: window(35, 50),
      harvestDurationDays: 60,
      temperature: temp([25, 30], [18, 25]),
      rotationYears: 3,
      tasks: [
        { kind: 'stake', afterDays: 1, note: '植え付けと同時にネットか支柱を' },
        { kind: 'pinch', afterDays: 20, note: '5 節目までの脇芽と雌花を取る' },
      ],
      commonPests: ['うどんこ病', 'アブラムシ', 'ウリハムシ'],
      tips: '成りはじめたら毎日見る。採り遅れるとヘチマのようになり株も疲れる。',
    },
    editorial: { beginner: true, container: container(30) },
  },
  {
    id: 'crop-nasu',
    name: 'ナス',
    nameReading: 'なす',
    family: 'ナス科',
    category: 'fruit',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'nagano-kasai-ondo'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 9 },
      { region: 'temperate', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'temperate', kind: 'harvest', startMonth: 6, endMonth: 10 },
      { region: 'warm', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 6, endMonth: 10 },
    ],
    guide: {
      spacingCm: 50,
      sunlight: 'full',
      wateringNote: '水食い。夏は朝夕 2 回。乾くとツヤのない実（ボケナス）になる。',
      wateringIntervalDays: 1,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 15,
      fertilizeIntervalDays: 15,
      harvestAfterDays: 55,
      harvestWindowDays: window(45, 65),
      harvestDurationDays: 100,
      temperature: temp([25, 35], [23, 28]),
      rotationYears: 4,
      tasks: [
        { kind: 'stake', afterDays: 1, note: '植え付けと同時に' },
        { kind: 'sucker', afterDays: 20, note: '一番花の下の脇芽を 2 本残して 3 本仕立てに' },
        { kind: 'pinch', afterDays: 90, note: '7 月末に更新剪定すると秋ナスが採れる' },
      ],
      commonPests: ['アブラムシ', 'テントウムシダマシ', 'ハダニ'],
      tips: '3 本仕立てが基本。7 月末に切り戻す（更新剪定）と秋ナスが楽しめる。',
    },
    editorial: { beginner: true, container: container(30) },
  },
  {
    id: 'crop-piiman',
    name: 'ピーマン',
    nameReading: 'ぴーまん',
    family: 'ナス科',
    category: 'fruit',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'nagano-kasai-ondo', 'okinawa-tokusai'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 9 },
      { region: 'temperate', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'temperate', kind: 'harvest', startMonth: 6, endMonth: 10 },
      { region: 'warm', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 6, endMonth: 11 },
    ],
    guide: {
      spacingCm: 45,
      sunlight: 'full',
      wateringNote: '乾燥に弱い。表面が乾いたらたっぷり。',
      wateringIntervalDays: 2,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 15,
      harvestAfterDays: 55,
      harvestWindowDays: window(45, 65),
      harvestDurationDays: 120,
      temperature: temp([28, 30], [25, 30]),
      rotationYears: 3,
      tasks: [
        { kind: 'stake', afterDays: 1, note: '植え付けと同時に' },
        { kind: 'sucker', afterDays: 20, note: '一番花より下の脇芽はすべて取る' },
      ],
      commonPests: ['アブラムシ', 'タバコガ', 'カメムシ'],
      tips: '一番花より下の脇芽はすべて取る。次々成るので若どりすると株が長持ちする。',
    },
    editorial: { beginner: true, container: container(30) },
  },
  {
    id: 'crop-okura',
    name: 'オクラ',
    nameReading: 'おくら',
    family: 'アオイ科',
    category: 'fruit',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'okinawa-tokusai'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 6, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 9 },
      { region: 'temperate', kind: 'sow', startMonth: 5, endMonth: 6 },
      { region: 'temperate', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'warm', kind: 'sow', startMonth: 4, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 6, endMonth: 10 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'full',
      wateringNote: '発芽まで湿らせる。真夏は乾いたらたっぷり。',
      wateringIntervalDays: 2,
      germinationDays: 7,
      transplantAfterDays: null,
      fertilizeAfterDays: 30,
      fertilizeIntervalDays: 15,
      harvestAfterDays: 60,
      harvestWindowDays: window(50, 70),
      harvestDurationDays: 90,
      temperature: temp([25, 30], [20, 30]),
      rotationYears: 1,
      tasks: [{ kind: 'thin', afterDays: 20, note: '本葉 2〜3 枚で 1 か所 2 本に' }],
      commonPests: ['アブラムシ', 'ハスモンヨトウ', 'カメムシ'],
      tips: '花が咲いて 4〜5 日で収穫。1 日採り遅れただけで固くなる。',
    },
    editorial: { beginner: true, container: container(30) },
  },
  {
    id: 'crop-edamame',
    name: 'エダマメ',
    nameReading: 'えだまめ',
    family: 'マメ科',
    category: 'bean',
    defaultUnit: 'bunch',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'nagano-kasai-ondo'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 8, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 4, endMonth: 6 },
      { region: 'temperate', kind: 'harvest', startMonth: 7, endMonth: 9 },
      { region: 'warm', kind: 'sow', startMonth: 4, endMonth: 6 },
      { region: 'warm', kind: 'harvest', startMonth: 6, endMonth: 9 },
    ],
    guide: {
      spacingCm: 25,
      sunlight: 'full',
      wateringNote: '開花〜さやの太る時期に乾かすと実入りが悪くなる。',
      wateringIntervalDays: 3,
      germinationDays: 5,
      transplantAfterDays: null,
      fertilizeAfterDays: null,
      fertilizeIntervalDays: null,
      harvestAfterDays: 80,
      harvestWindowDays: window(75, 90),
      harvestDurationDays: 10,
      temperature: temp([25, 30], [20, 25]),
      rotationYears: 2,
      tasks: [
        { kind: 'net', afterDays: 1, note: '鳥に種を食べられるので発芽までかける' },
        { kind: 'hill', afterDays: 25, note: '本葉 5 枚で。倒れにくくなる' },
      ],
      commonPests: ['カメムシ', 'アブラムシ', 'マメシンクイガ'],
      tips: '根に付く根粒菌が肥料を作るので追肥はほぼ不要。やりすぎると葉ばかり茂る。',
    },
    editorial: { beginner: true, container: container(25) },
  },
  {
    id: 'crop-toumorokoshi',
    name: 'トウモロコシ',
    nameReading: 'とうもろこし',
    family: 'イネ科',
    category: 'fruit',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'nagano-kasai-ondo'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 8, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 4, endMonth: 5 },
      { region: 'temperate', kind: 'harvest', startMonth: 7, endMonth: 8 },
      { region: 'warm', kind: 'sow', startMonth: 3, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 6, endMonth: 8 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'full',
      wateringNote: '雄穂が出てから実が太るまでは水を切らさない。',
      wateringIntervalDays: 3,
      germinationDays: 6,
      transplantAfterDays: null,
      fertilizeAfterDays: 30,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 85,
      harvestWindowDays: window(80, 95),
      harvestDurationDays: 7,
      temperature: temp([30, 35], [22, 30]),
      rotationYears: 0,
      tasks: [
        { kind: 'thin', afterDays: 20, note: '本葉 3〜4 枚で 1 本に' },
        { kind: 'hill', afterDays: 30, note: '追肥と一緒に。倒伏を防ぐ' },
        {
          kind: 'fruit-thin',
          afterDays: 60,
          note: '雌穂は 1 本に 1 つ残す（ヤングコーンとして食べる）',
        },
      ],
      commonPests: ['アワノメイガ', 'アブラムシ', 'カラスなどの鳥害'],
      tips: '1 列より 2 列以上のかたまりで植えると受粉が安定して歯抜けになりにくい。',
    },
    editorial: { beginner: false, container: NO_CONTAINER },
  },
  {
    id: 'crop-kabocha',
    name: 'カボチャ',
    nameReading: 'かぼちゃ',
    family: 'ウリ科',
    category: 'fruit',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'nagano-kasai-ondo', 'okinawa-tokusai'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 8, endMonth: 9 },
      { region: 'temperate', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'temperate', kind: 'harvest', startMonth: 7, endMonth: 9 },
      { region: 'warm', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 7, endMonth: 9 },
    ],
    guide: {
      spacingCm: 90,
      sunlight: 'full',
      wateringNote: '乾燥に強い。植え付け直後以外はほぼ雨まかせでよい。',
      wateringIntervalDays: null,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 30,
      fertilizeIntervalDays: null,
      harvestAfterDays: 90,
      harvestWindowDays: window(80, 100),
      harvestDurationDays: null,
      temperature: temp([25, 28], [20, 22]),
      rotationYears: 0,
      tasks: [
        { kind: 'pinch', afterDays: 20, note: '本葉 5〜6 枚で親づるを止め、子づる 2〜3 本に' },
        { kind: 'fruit-thin', afterDays: 50, note: '1 つるに 2 個まで' },
      ],
      commonPests: ['うどんこ病', 'ウリハムシ', 'アブラムシ'],
      tips: 'ヘタがコルク状にひび割れたら収穫。採ってから 1〜2 週間置くと甘くなる。',
    },
    editorial: { beginner: true, container: NO_CONTAINER },
  },
  {
    id: 'crop-goya',
    name: 'ゴーヤ',
    nameReading: 'ごーや',
    family: 'ウリ科',
    category: 'fruit',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'okinawa-tokusai'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 6, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 8, endMonth: 9 },
      { region: 'temperate', kind: 'plant', startMonth: 5, endMonth: 5 },
      { region: 'temperate', kind: 'harvest', startMonth: 7, endMonth: 9 },
      { region: 'warm', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 6, endMonth: 10 },
    ],
    guide: {
      spacingCm: 50,
      sunlight: 'full',
      wateringNote: '真夏は毎朝たっぷり。プランターの緑のカーテンは特に乾きやすい。',
      wateringIntervalDays: 1,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 50,
      harvestWindowDays: window(45, 60),
      harvestDurationDays: 70,
      temperature: temp([25, 30], [20, 30]),
      rotationYears: 0,
      tasks: [
        { kind: 'stake', afterDays: 1, note: 'ネットか支柱を植え付けと同時に' },
        { kind: 'pinch', afterDays: 20, note: '本葉 5〜6 枚で親づるを摘芯' },
      ],
      commonPests: ['アブラムシ', 'ウリハムシ'],
      tips: '本葉 5〜6 枚で摘芯すると子づるが伸びて収量が増える。緑のカーテンにも向く。',
    },
    editorial: { beginner: true, container: container(30) },
  },
  {
    id: 'crop-zucchini',
    name: 'ズッキーニ',
    nameReading: 'ずっきーに',
    family: 'ウリ科',
    category: 'fruit',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 8 },
      { region: 'temperate', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'temperate', kind: 'harvest', startMonth: 6, endMonth: 8 },
      { region: 'warm', kind: 'plant', startMonth: 4, endMonth: 4 },
      { region: 'warm', kind: 'harvest', startMonth: 5, endMonth: 8 },
    ],
    guide: {
      spacingCm: 80,
      sunlight: 'full',
      wateringNote: '朝にたっぷり。葉が大きく蒸散が多い。',
      wateringIntervalDays: 2,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 15,
      harvestAfterDays: 45,
      harvestWindowDays: window(40, 55),
      harvestDurationDays: 50,
      temperature: temp([25, 30], [18, 25]),
      rotationYears: 2,
      tasks: [{ kind: 'stake', afterDays: 30, note: '倒れやすいので株を支柱に結ぶ' }],
      commonPests: ['うどんこ病', 'アブラムシ', 'ウリハムシ'],
      tips: '朝のうちに雄花の花粉を雌花に付ける（人工授粉）と着果が安定。実は 20cm までに採る。',
    },
    editorial: { beginner: false, container: NO_CONTAINER },
  },
  {
    id: 'crop-jagaimo',
    name: 'ジャガイモ',
    nameReading: 'じゃがいも',
    family: 'ナス科',
    category: 'tuber',
    defaultUnit: 'kg',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'nagasaki-potato', 'maff-potato', 'maff-akita-konsai'],
    calendars: [
      // 中間地・暖地は春植えと秋植えの 2 期作（同じ kind に 2 窓）
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 5 },
      { region: 'cold', kind: 'harvest', startMonth: 8, endMonth: 9 },
      { region: 'temperate', kind: 'plant', startMonth: 2, endMonth: 3 },
      { region: 'temperate', kind: 'plant', startMonth: 8, endMonth: 9 },
      { region: 'temperate', kind: 'harvest', startMonth: 5, endMonth: 6 },
      { region: 'temperate', kind: 'harvest', startMonth: 11, endMonth: 12 },
      { region: 'warm', kind: 'plant', startMonth: 2, endMonth: 3 },
      { region: 'warm', kind: 'plant', startMonth: 8, endMonth: 9 },
      { region: 'warm', kind: 'harvest', startMonth: 5, endMonth: 6 },
      { region: 'warm', kind: 'harvest', startMonth: 11, endMonth: 12 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'full',
      wateringNote: '植え付け後は控えめ。過湿は種芋が腐るいちばんの原因。',
      wateringIntervalDays: null,
      germinationDays: 25,
      transplantAfterDays: null,
      fertilizeAfterDays: 30,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 100,
      harvestWindowDays: window(90, 110),
      harvestDurationDays: null,
      temperature: temp([15, 20], [15, 20]),
      rotationYears: 3,
      tasks: [
        { kind: 'sucker', afterDays: 35, note: '芽が 10cm で 2〜3 本に' },
        { kind: 'hill', afterDays: 35, note: '芽かきと一緒に 1 回目' },
        { kind: 'hill', afterDays: 55, note: '2 回目。芋が日に当たると緑化する' },
      ],
      commonPests: ['テントウムシダマシ', 'アブラムシ', 'そうか病'],
      tips: '芽かきで 2〜3 本に。芋が日に当たると緑化して食べられないので土寄せを 2 回。',
    },
    editorial: { beginner: true, container: container(30) },
  },
  {
    id: 'crop-satsumaimo',
    name: 'サツマイモ',
    nameReading: 'さつまいも',
    family: 'ヒルガオ科',
    category: 'tuber',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'maff-akita-konsai'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 6, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'plant', startMonth: 5, endMonth: 6 },
      { region: 'temperate', kind: 'harvest', startMonth: 10, endMonth: 11 },
      { region: 'warm', kind: 'plant', startMonth: 5, endMonth: 6 },
      { region: 'warm', kind: 'harvest', startMonth: 10, endMonth: 11 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'full',
      wateringNote: '植え付け後 1 週間だけ乾かさない。あとはほぼ不要。',
      wateringIntervalDays: null,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: null,
      fertilizeIntervalDays: null,
      harvestAfterDays: 120,
      harvestWindowDays: window(110, 150),
      harvestDurationDays: null,
      temperature: temp([25, 30], [22, 30]),
      rotationYears: 0,
      tasks: [{ kind: 'pinch', afterDays: 60, note: 'つる返し。伸びたつるを持ち上げて根を切る' }],
      commonPests: ['コガネムシの幼虫', 'ハスモンヨトウ'],
      tips: '肥料が残る土だとツルばかり茂る（ツルぼけ）。夏につる返しをして芋に養分を集める。',
    },
    editorial: { beginner: true, container: container(30) },
  },
  {
    id: 'crop-ichigo',
    name: 'イチゴ',
    nameReading: 'いちご',
    family: 'バラ科',
    category: 'fruit',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'nagano-kasai-ondo', 'takii-manual'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 9, endMonth: 9 },
      { region: 'cold', kind: 'harvest', startMonth: 6, endMonth: 7 },
      { region: 'temperate', kind: 'plant', startMonth: 10, endMonth: 11 },
      { region: 'temperate', kind: 'harvest', startMonth: 4, endMonth: 6 },
      { region: 'warm', kind: 'plant', startMonth: 10, endMonth: 11 },
      { region: 'warm', kind: 'harvest', startMonth: 3, endMonth: 5 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'full',
      wateringNote: '乾いたら株元に。実に水がかかると傷みやすい。',
      wateringIntervalDays: 3,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 150,
      fertilizeIntervalDays: 30,
      harvestAfterDays: 210,
      harvestWindowDays: window(180, 240),
      harvestDurationDays: 45,
      temperature: temp([18, 23], [18, 23]),
      rotationYears: 2,
      tasks: [{ kind: 'pinch', afterDays: 150, note: '春先にランナーと枯れ葉を取り、敷きわらを' }],
      commonPests: ['アブラムシ', 'ハダニ', 'うどんこ病'],
      tips: '花はランナーの反対側に付く。実の下にマルチや敷きわらを入れると汚れと病気を防げる。',
    },
    editorial: { beginner: false, container: container(20) },
  },
  {
    id: 'crop-hanegi',
    name: '葉ネギ',
    nameReading: 'はねぎ',
    family: 'ヒガンバナ科',
    category: 'allium',
    defaultUnit: 'bunch',
    sourceIds: ['maff-sehi', 'takii-manual'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 4, endMonth: 5 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 9 },
      { region: 'temperate', kind: 'sow', startMonth: 3, endMonth: 4 },
      { region: 'temperate', kind: 'harvest', startMonth: 6, endMonth: 11 },
      { region: 'warm', kind: 'sow', startMonth: 3, endMonth: 4 },
      { region: 'warm', kind: 'harvest', startMonth: 5, endMonth: 12 },
    ],
    guide: {
      spacingCm: 5,
      sunlight: 'full',
      wateringNote: '表面が乾いたら。プランターでも育てやすい。',
      wateringIntervalDays: 3,
      germinationDays: 10,
      transplantAfterDays: null,
      fertilizeAfterDays: 30,
      fertilizeIntervalDays: 30,
      harvestAfterDays: 60,
      harvestWindowDays: window(50, 80),
      harvestDurationDays: 120,
      temperature: temp([15, 25], [15, 20]),
      rotationYears: 0,
      tasks: [],
      commonPests: ['アブラムシ', 'さび病', 'ネギアザミウマ'],
      tips: '根元を 3cm ほど残して刈ると再生して何度も採れる。台所のプランター向き。',
    },
    editorial: { beginner: true, container: container(15) },
  },
  {
    id: 'crop-snap-endou',
    name: 'スナップエンドウ',
    nameReading: 'すなっぷえんどう',
    family: 'マメ科',
    category: 'bean',
    defaultUnit: 'bunch',
    sourceIds: ['maff-sehi', 'nagano-kasai-ondo', 'takii-manual'],
    calendars: [
      // 寒冷地は春まき、中間地・暖地は秋まきで冬越し
      { region: 'cold', kind: 'sow', startMonth: 4, endMonth: 5 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 8 },
      { region: 'temperate', kind: 'sow', startMonth: 10, endMonth: 11 },
      { region: 'temperate', kind: 'harvest', startMonth: 4, endMonth: 6 },
      { region: 'warm', kind: 'sow', startMonth: 10, endMonth: 11 },
      { region: 'warm', kind: 'harvest', startMonth: 3, endMonth: 5 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'full',
      wateringNote: '開花期に乾かさない。冬の間は控えめでよい。',
      wateringIntervalDays: 4,
      germinationDays: 7,
      transplantAfterDays: null,
      fertilizeAfterDays: 120,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 180,
      harvestWindowDays: window(170, 200),
      harvestDurationDays: 40,
      temperature: temp([18, 20], [15, 20]),
      rotationYears: 4,
      tasks: [{ kind: 'stake', afterDays: 120, note: '春につるが伸び始めたらネットか支柱を' }],
      commonPests: ['うどんこ病', 'ハモグリバエ', 'アブラムシ'],
      tips: '秋まきは本葉 2〜3 枚の小苗で冬越しさせるのがいちばん寒さに強い。大きくしすぎない。',
    },
    editorial: { beginner: true, container: container(25) },
  },
  {
    id: 'crop-shiso',
    name: 'シソ',
    nameReading: 'しそ',
    family: 'シソ科',
    category: 'herb',
    defaultUnit: 'bunch',
    sourceIds: ['maff-sehi', 'jeinou-calendar'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 9 },
      { region: 'temperate', kind: 'sow', startMonth: 4, endMonth: 6 },
      { region: 'temperate', kind: 'harvest', startMonth: 6, endMonth: 10 },
      { region: 'warm', kind: 'sow', startMonth: 4, endMonth: 6 },
      { region: 'warm', kind: 'harvest', startMonth: 6, endMonth: 10 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'partial',
      wateringNote: '乾燥すると葉が固くなる。半日陰でこまめに水やりすると柔らかく育つ。',
      wateringIntervalDays: 2,
      germinationDays: 10,
      transplantAfterDays: null,
      fertilizeAfterDays: 30,
      fertilizeIntervalDays: 30,
      harvestAfterDays: 40,
      harvestWindowDays: window(30, 50),
      harvestDurationDays: 100,
      temperature: temp([20, 25], [20, 25]),
      rotationYears: 0,
      tasks: [{ kind: 'pinch', afterDays: 35, note: '草丈 30cm で芯を止めて脇芽を増やす' }],
      commonPests: ['ハダニ', 'バッタ', 'ヨトウムシ'],
      tips: '摘芯して脇芽を増やすと長く採れる。こぼれ種で翌年も生えてくる。',
    },
    editorial: { beginner: true, container: container(15) },
  },
  {
    id: 'crop-basil',
    name: 'バジル',
    nameReading: 'ばじる',
    family: 'シソ科',
    category: 'herb',
    defaultUnit: 'bunch',
    sourceIds: ['maff-sehi', 'jeinou-calendar'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 6, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 9 },
      { region: 'temperate', kind: 'plant', startMonth: 5, endMonth: 6 },
      { region: 'temperate', kind: 'harvest', startMonth: 6, endMonth: 10 },
      { region: 'warm', kind: 'plant', startMonth: 4, endMonth: 6 },
      { region: 'warm', kind: 'harvest', startMonth: 6, endMonth: 10 },
    ],
    guide: {
      spacingCm: 25,
      sunlight: 'full',
      wateringNote: '水好き。表面が乾いたらたっぷり。',
      wateringIntervalDays: 2,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 30,
      harvestWindowDays: window(25, 40),
      harvestDurationDays: 100,
      temperature: temp([20, 25], [20, 30]),
      rotationYears: 0,
      tasks: [{ kind: 'pinch', afterDays: 25, note: '本葉 8〜10 枚で芯を止める。花穂も摘む' }],
      commonPests: ['アブラムシ', 'ハダニ', 'ベニフキノメイガ'],
      tips: '花穂が付いたら早めに摘む（葉が固くなる）。摘芯するたびに収量が増える。',
    },
    editorial: { beginner: true, container: container(15) },
  },
  {
    id: 'crop-retasu',
    name: 'レタス',
    nameReading: 'れたす',
    family: 'キク科',
    category: 'leaf',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'ja-hokkaido', 'okinawa-tokusai', 'takii-manual'],
    calendars: [
      // 中間地・暖地は春と秋の 2 期作
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 8 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'temperate', kind: 'plant', startMonth: 3, endMonth: 4 },
      { region: 'temperate', kind: 'plant', startMonth: 9, endMonth: 9 },
      { region: 'temperate', kind: 'harvest', startMonth: 5, endMonth: 6 },
      { region: 'temperate', kind: 'harvest', startMonth: 11, endMonth: 12 },
      { region: 'warm', kind: 'plant', startMonth: 2, endMonth: 3 },
      { region: 'warm', kind: 'plant', startMonth: 9, endMonth: 10 },
      { region: 'warm', kind: 'harvest', startMonth: 4, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 11, endMonth: 1 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'full',
      wateringNote: '朝に。結球が始まったら控えめにすると病気が出にくい。',
      wateringIntervalDays: 3,
      germinationDays: 4,
      transplantAfterDays: 30,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: null,
      harvestAfterDays: 60,
      harvestWindowDays: window(50, 70),
      harvestDurationDays: null,
      temperature: temp([15, 20], [15, 20]),
      rotationYears: 2,
      tasks: [],
      commonPests: ['アブラムシ', 'ナメクジ', 'ヨトウムシ'],
      tips: '高温だと発芽しない。夏まきは濡らした種を冷蔵庫で 2〜3 日芽出ししてからまく。',
    },
    editorial: { beginner: false, container: container(20) },
  },
  // ─── 4.19 第 1 段（v4）: 穴として現れていたものと家庭菜園の頻出 20 品目 ──────
  {
    id: 'crop-rukkora',
    name: 'ルッコラ',
    nameReading: 'るっこら',
    family: 'アブラナ科',
    category: 'leaf',
    defaultUnit: 'bunch',
    sourceIds: ['ja-hareoka-rukkora', 'jeinou-calendar'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 4, endMonth: 8 },
      { region: 'cold', kind: 'harvest', startMonth: 5, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 3, endMonth: 5 },
      { region: 'temperate', kind: 'sow', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'harvest', startMonth: 4, endMonth: 6 },
      { region: 'temperate', kind: 'harvest', startMonth: 10, endMonth: 12 },
      { region: 'warm', kind: 'sow', startMonth: 3, endMonth: 5 },
      { region: 'warm', kind: 'sow', startMonth: 9, endMonth: 11 },
      { region: 'warm', kind: 'harvest', startMonth: 4, endMonth: 6 },
      { region: 'warm', kind: 'harvest', startMonth: 10, endMonth: 1 },
    ],
    guide: {
      spacingCm: 8,
      sunlight: 'full',
      wateringNote: '乾かすと葉が固く辛くなる。表面が乾いたらたっぷり。真夏は半日陰に。',
      wateringIntervalDays: 2,
      germinationDays: 3,
      transplantAfterDays: null,
      fertilizeAfterDays: 15,
      fertilizeIntervalDays: null,
      harvestAfterDays: 35,
      harvestWindowDays: window(30, 45),
      harvestDurationDays: 30,
      temperature: temp([15, 20], [15, 20]),
      rotationYears: 1,
      tasks: [
        { kind: 'thin', afterDays: 7, note: '2〜3cm 間隔に' },
        { kind: 'thin', afterDays: 20, note: '本葉 5 枚で 8cm 間隔に' },
      ],
      commonPests: ['アブラムシ', 'コナガ', 'キスジノミハムシ'],
      tips: '葉が 15cm を超えたら外葉から摘み取ると長く採れる。高温でとう立ちしやすいので春は早めに。',
    },
    editorial: { beginner: true, container: container(15) },
  },
  {
    id: 'crop-kushinsai',
    name: '空芯菜',
    nameReading: 'くうしんさい',
    family: 'ヒルガオ科',
    category: 'leaf',
    defaultUnit: 'bunch',
    sourceIds: ['ja-kiso-kushinsai', 'jeinou-calendar'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 6, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 9 },
      { region: 'temperate', kind: 'sow', startMonth: 5, endMonth: 6 },
      { region: 'temperate', kind: 'harvest', startMonth: 6, endMonth: 10 },
      { region: 'warm', kind: 'sow', startMonth: 4, endMonth: 6 },
      { region: 'warm', kind: 'harvest', startMonth: 6, endMonth: 10 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'full',
      wateringNote: '水を好み乾燥に弱い。夏は毎朝たっぷり。',
      wateringIntervalDays: 1,
      germinationDays: 7,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 15,
      harvestAfterDays: 45,
      harvestWindowDays: window(40, 60),
      harvestDurationDays: 90,
      temperature: temp([25, 30], [25, 30]),
      rotationYears: 0,
      tasks: [{ kind: 'pinch', afterDays: 40, note: '草丈 30cm で株元 3 節を残して摘み取る' }],
      commonPests: ['ハスモンヨトウ', 'アブラムシ'],
      tips: '種は一晩水につけてからまくと発芽がそろう。摘めば摘むほど脇芽が出て秋まで採れる。',
    },
    editorial: { beginner: true, container: container(20) },
  },
  {
    id: 'crop-chingensai',
    name: 'チンゲンサイ',
    nameReading: 'ちんげんさい',
    family: 'アブラナ科',
    category: 'leaf',
    defaultUnit: 'plant',
    sourceIds: ['okinawa-tokusai', 'jeinou-calendar'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 8 },
      { region: 'cold', kind: 'harvest', startMonth: 6, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 3, endMonth: 4 },
      { region: 'temperate', kind: 'sow', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'harvest', startMonth: 5, endMonth: 6 },
      { region: 'temperate', kind: 'harvest', startMonth: 10, endMonth: 12 },
      { region: 'warm', kind: 'sow', startMonth: 3, endMonth: 4 },
      { region: 'warm', kind: 'sow', startMonth: 9, endMonth: 11 },
      { region: 'warm', kind: 'harvest', startMonth: 4, endMonth: 6 },
      { region: 'warm', kind: 'harvest', startMonth: 10, endMonth: 1 },
    ],
    guide: {
      spacingCm: 15,
      sunlight: 'full',
      wateringNote: '表面が乾いたらたっぷり。水切れすると葉が固くなる。',
      wateringIntervalDays: 2,
      germinationDays: 3,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: null,
      harvestAfterDays: 45,
      harvestWindowDays: window(40, 55),
      harvestDurationDays: null,
      temperature: temp([20, 25], [15, 25]),
      rotationYears: 1,
      tasks: [
        { kind: 'net', afterDays: 1, note: '種まき直後にかける' },
        { kind: 'thin', afterDays: 14, note: '本葉 3〜4 枚で 15cm 間隔に' },
      ],
      commonPests: ['アブラムシ', 'コナガ', 'アオムシ'],
      tips: '株元がふくらんで尻張りしてきたら収穫。ミニチンゲンサイなら 30 日で採れる。',
    },
    editorial: { beginner: true, container: container(15) },
  },
  {
    id: 'crop-moroheiya',
    name: 'モロヘイヤ',
    nameReading: 'もろへいや',
    family: 'アオイ科',
    category: 'leaf',
    defaultUnit: 'bunch',
    sourceIds: ['ja-nishikasugai-moroheiya', 'jeinou-calendar'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 6, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 9 },
      { region: 'temperate', kind: 'sow', startMonth: 4, endMonth: 6 },
      { region: 'temperate', kind: 'plant', startMonth: 6, endMonth: 7 },
      { region: 'temperate', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'warm', kind: 'sow', startMonth: 4, endMonth: 5 },
      { region: 'warm', kind: 'plant', startMonth: 5, endMonth: 6 },
      { region: 'warm', kind: 'harvest', startMonth: 6, endMonth: 10 },
    ],
    guide: {
      spacingCm: 50,
      sunlight: 'full',
      wateringNote: '乾燥には強いが、水が切れると葉が固くなる。夏は朝にたっぷり。',
      wateringIntervalDays: 2,
      germinationDays: 7,
      transplantAfterDays: 30,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 60,
      harvestWindowDays: window(50, 70),
      harvestDurationDays: 90,
      temperature: temp([25, 30], [25, 30]),
      rotationYears: 0,
      tasks: [{ kind: 'pinch', afterDays: 40, note: '草丈 30cm で先端を摘んで脇芽を増やす' }],
      commonPests: ['ハダニ', 'アブラムシ', 'ハスモンヨトウ'],
      tips: '先端 15cm を摘み取り収穫。種とさやには毒があるので花が咲いたら食べない。',
    },
    editorial: { beginner: true, container: container(25) },
  },
  {
    id: 'crop-sanchu',
    name: 'サンチュ',
    nameReading: 'さんちゅ',
    family: 'キク科',
    category: 'leaf',
    defaultUnit: 'plant',
    sourceIds: ['ja-hareoka-sanchu', 'jeinou-calendar'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 8 },
      { region: 'cold', kind: 'harvest', startMonth: 6, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 3, endMonth: 4 },
      { region: 'temperate', kind: 'sow', startMonth: 8, endMonth: 9 },
      { region: 'temperate', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'temperate', kind: 'plant', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'harvest', startMonth: 5, endMonth: 7 },
      { region: 'temperate', kind: 'harvest', startMonth: 10, endMonth: 12 },
      { region: 'warm', kind: 'plant', startMonth: 3, endMonth: 4 },
      { region: 'warm', kind: 'plant', startMonth: 9, endMonth: 10 },
      { region: 'warm', kind: 'harvest', startMonth: 4, endMonth: 6 },
      { region: 'warm', kind: 'harvest', startMonth: 10, endMonth: 1 },
    ],
    guide: {
      spacingCm: 25,
      sunlight: 'full',
      wateringNote: '表面が乾いたら。かき取りを続けるので水切れさせない。',
      wateringIntervalDays: 2,
      germinationDays: 4,
      transplantAfterDays: 30,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 40,
      harvestWindowDays: window(30, 50),
      harvestDurationDays: 90,
      temperature: temp([15, 20], [15, 20]),
      rotationYears: 2,
      tasks: [],
      commonPests: ['アブラムシ', 'ナメクジ', 'ヨトウムシ'],
      tips: '下の葉から 1 枚ずつかき取ると数か月採れる。25℃ を超えるととう立ちするので初心者は秋まきが楽。',
    },
    editorial: { beginner: true, container: container(15) },
  },
  {
    id: 'crop-karifurawa',
    name: 'カリフラワー',
    nameReading: 'かりふらわー',
    family: 'アブラナ科',
    category: 'leaf',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'takii-manual'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 7 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'temperate', kind: 'plant', startMonth: 8, endMonth: 9 },
      { region: 'temperate', kind: 'harvest', startMonth: 11, endMonth: 1 },
      { region: 'warm', kind: 'plant', startMonth: 9, endMonth: 10 },
      { region: 'warm', kind: 'harvest', startMonth: 12, endMonth: 2 },
    ],
    guide: {
      spacingCm: 45,
      sunlight: 'full',
      wateringNote: '植え付け後 2 週間は乾かさない。以後は表面が乾いたら。',
      wateringIntervalDays: 3,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 90,
      harvestWindowDays: window(80, 100),
      harvestDurationDays: null,
      temperature: temp([20, 25], [15, 20]),
      rotationYears: 2,
      tasks: [
        { kind: 'net', afterDays: 1, note: '植え付けと同時にかける' },
        { kind: 'hill', afterDays: 20, note: '追肥と一緒に' },
      ],
      commonPests: ['アオムシ', 'コナガ', 'アブラムシ'],
      tips: '花蕾が見えたら外葉で包んで日よけすると白く仕上がる。ブロッコリーと違い側花蕾は出ない。',
    },
    editorial: { beginner: false, container: NO_CONTAINER },
  },
  {
    id: 'crop-radisshu',
    name: 'ラディッシュ',
    nameReading: 'らでぃっしゅ',
    family: 'アブラナ科',
    category: 'root',
    defaultUnit: 'piece',
    sourceIds: ['jeinou-calendar', 'maff-sehi'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 9 },
      { region: 'cold', kind: 'harvest', startMonth: 6, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 3, endMonth: 6 },
      { region: 'temperate', kind: 'sow', startMonth: 9, endMonth: 11 },
      { region: 'temperate', kind: 'harvest', startMonth: 4, endMonth: 7 },
      { region: 'temperate', kind: 'harvest', startMonth: 10, endMonth: 12 },
      { region: 'warm', kind: 'sow', startMonth: 3, endMonth: 6 },
      { region: 'warm', kind: 'sow', startMonth: 9, endMonth: 11 },
      { region: 'warm', kind: 'harvest', startMonth: 4, endMonth: 7 },
      { region: 'warm', kind: 'harvest', startMonth: 10, endMonth: 1 },
    ],
    guide: {
      spacingCm: 5,
      sunlight: 'full',
      wateringNote: '乾き続けると根が割れる。表面が乾いたらたっぷり。',
      wateringIntervalDays: 2,
      germinationDays: 3,
      transplantAfterDays: null,
      fertilizeAfterDays: null,
      fertilizeIntervalDays: null,
      harvestAfterDays: 30,
      harvestWindowDays: window(25, 40),
      harvestDurationDays: null,
      temperature: temp([15, 30], [17, 20]),
      rotationYears: 1,
      tasks: [{ kind: 'thin', afterDays: 10, note: '本葉 2 枚で 5cm 間隔に' }],
      commonPests: ['アブラムシ', 'キスジノミハムシ'],
      tips: '二十日大根の名前どおり 1 か月で採れる。根の直径 2〜3cm で早めに収穫。遅れるとスが入る。',
    },
    editorial: { beginner: true, container: container(15) },
  },
  {
    id: 'crop-shoga',
    name: 'ショウガ',
    nameReading: 'しょうが',
    family: 'ショウガ科',
    category: 'root',
    defaultUnit: 'kg',
    sourceIds: ['saitama-shoga', 'jeinou-calendar'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 5 },
      { region: 'cold', kind: 'harvest', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'temperate', kind: 'harvest', startMonth: 10, endMonth: 11 },
      { region: 'warm', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 10, endMonth: 11 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'partial',
      wateringNote: '乾燥に弱い。夏は敷きわらをして朝にたっぷり。',
      wateringIntervalDays: 2,
      germinationDays: 30,
      transplantAfterDays: null,
      fertilizeAfterDays: 60,
      fertilizeIntervalDays: 30,
      harvestAfterDays: 180,
      harvestWindowDays: window(160, 200),
      harvestDurationDays: null,
      temperature: temp([25, 30], [25, 30]),
      rotationYears: 4,
      tasks: [
        { kind: 'hill', afterDays: 60, note: '芽が 2〜3 本出そろったら 1 回目。追肥と一緒に' },
        { kind: 'hill', afterDays: 90, note: '2 回目。根茎が露出しないように' },
      ],
      commonPests: ['アワノメイガ', 'ハスモンヨトウ', '根茎腐敗病'],
      tips: '地温 15℃ 以下では芽が出ない。急がず 4 月下旬以降に植える。夏の葉ショウガ、秋の根ショウガと二度楽しめる。',
    },
    editorial: { beginner: false, container: container(30) },
  },
  {
    id: 'crop-togarashi',
    name: 'トウガラシ',
    nameReading: 'とうがらし',
    family: 'ナス科',
    category: 'fruit',
    defaultUnit: 'piece',
    sourceIds: ['ja-nishikasugai-shishito', 'nagano-kasai-ondo'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 9 },
      { region: 'temperate', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'temperate', kind: 'harvest', startMonth: 6, endMonth: 10 },
      { region: 'warm', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 6, endMonth: 11 },
    ],
    guide: {
      spacingCm: 45,
      sunlight: 'full',
      wateringNote: '乾燥に弱い。表面が乾いたらたっぷり。水切れすると辛みが強くなる。',
      wateringIntervalDays: 2,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 15,
      fertilizeIntervalDays: 15,
      harvestAfterDays: 60,
      harvestWindowDays: window(50, 70),
      harvestDurationDays: 120,
      temperature: temp([25, 30], [25, 30]),
      rotationYears: 3,
      tasks: [
        { kind: 'stake', afterDays: 1, note: '枝が折れやすいので早めに' },
        { kind: 'sucker', afterDays: 20, note: '一番花の下の脇芽を取り 3 本仕立てに' },
      ],
      commonPests: ['アブラムシ', 'タバコガ', 'カメムシ'],
      tips: 'シシトウ・甘長も同じ育て方。最初の実は小さいうちに採ると株が育つ。',
    },
    editorial: { beginner: true, container: container(30) },
  },
  {
    id: 'crop-papurika',
    name: 'パプリカ',
    nameReading: 'ぱぷりか',
    family: 'ナス科',
    category: 'fruit',
    defaultUnit: 'piece',
    sourceIds: ['ja-kiso-papurika', 'nagano-kasai-ondo'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 8, endMonth: 9 },
      { region: 'temperate', kind: 'plant', startMonth: 5, endMonth: 5 },
      { region: 'temperate', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'warm', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 7, endMonth: 11 },
    ],
    guide: {
      spacingCm: 50,
      sunlight: 'full',
      wateringNote: '乾燥に弱い。実が色づくまで長いので水と肥料を切らさない。',
      wateringIntervalDays: 2,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 20,
      fertilizeIntervalDays: 15,
      harvestAfterDays: 80,
      harvestWindowDays: window(70, 100),
      harvestDurationDays: 90,
      temperature: temp([28, 30], [22, 30]),
      rotationYears: 3,
      tasks: [
        { kind: 'stake', afterDays: 1, note: '実が重いので植え付けと同時に' },
        { kind: 'sucker', afterDays: 20, note: '一番花の下の脇芽を取り 3 本仕立てに' },
        { kind: 'fruit-thin', afterDays: 40, note: '最初の 1〜2 個は青いうちに採って株を育てる' },
      ],
      commonPests: ['アブラムシ', 'タバコガ', '尻腐れ（カルシウム不足）'],
      tips: '開花から色づくまで 50〜60 日かかる。ピーマンより難しいが、緑のまま採れば失敗しない。',
    },
    editorial: { beginner: false, container: container(30) },
  },
  {
    id: 'crop-suika',
    name: 'スイカ',
    nameReading: 'すいか',
    family: 'ウリ科',
    category: 'fruit',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'nagano-kasai-ondo', 'takii-manual'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 8, endMonth: 9 },
      { region: 'temperate', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'temperate', kind: 'harvest', startMonth: 7, endMonth: 8 },
      { region: 'warm', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 7, endMonth: 8 },
    ],
    guide: {
      spacingCm: 100,
      sunlight: 'full',
      wateringNote: '乾燥に強い。実が太る時期以外は控えめ。収穫前は水を切ると甘くなる。',
      wateringIntervalDays: 4,
      germinationDays: null,
      transplantAfterDays: null,
      fertilizeAfterDays: 30,
      fertilizeIntervalDays: null,
      harvestAfterDays: 90,
      harvestWindowDays: window(80, 100),
      harvestDurationDays: 20,
      temperature: temp([25, 30], [23, 28]),
      rotationYears: 4,
      tasks: [
        { kind: 'pinch', afterDays: 15, note: '本葉 5〜6 枚で親づるを止め、子づる 3 本に' },
        { kind: 'fruit-thin', afterDays: 50, note: '1 つるに 1 個。受粉日を札に書く' },
      ],
      commonPests: ['うどんこ病', 'つる割病', 'ウリハムシ'],
      tips: '受粉から 35〜45 日が収穫の目安。巻きひげが枯れ、叩いて濁った音がしたら採りどき。',
    },
    editorial: { beginner: false, container: NO_CONTAINER },
  },
  {
    id: 'crop-ingen',
    name: 'インゲン',
    nameReading: 'いんげん',
    family: 'マメ科',
    category: 'bean',
    defaultUnit: 'g',
    sourceIds: ['okinawa-tokusai', 'nagano-kasai-ondo', 'takii-manual'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 7 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 9 },
      { region: 'temperate', kind: 'sow', startMonth: 4, endMonth: 6 },
      { region: 'temperate', kind: 'sow', startMonth: 8, endMonth: 8 },
      { region: 'temperate', kind: 'harvest', startMonth: 6, endMonth: 8 },
      { region: 'temperate', kind: 'harvest', startMonth: 9, endMonth: 10 },
      { region: 'warm', kind: 'sow', startMonth: 4, endMonth: 6 },
      { region: 'warm', kind: 'sow', startMonth: 8, endMonth: 9 },
      { region: 'warm', kind: 'harvest', startMonth: 6, endMonth: 8 },
      { region: 'warm', kind: 'harvest', startMonth: 9, endMonth: 11 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'full',
      wateringNote: '開花〜さやが太る時期に乾かすと落花する。表面が乾いたらたっぷり。',
      wateringIntervalDays: 3,
      germinationDays: 5,
      transplantAfterDays: null,
      fertilizeAfterDays: 25,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 55,
      harvestWindowDays: window(50, 65),
      harvestDurationDays: 30,
      temperature: temp([20, 25], [15, 25]),
      rotationYears: 2,
      tasks: [
        { kind: 'net', afterDays: 1, note: '鳥に種を食べられるので発芽までかける' },
        { kind: 'stake', afterDays: 20, note: 'つるあり種はネットか支柱を' },
      ],
      commonPests: ['アブラムシ', 'ハダニ', 'カメムシ'],
      tips: 'つるなし種なら支柱いらずで 50 日ほど。若いさやをこまめに採ると長く成る。',
    },
    editorial: { beginner: true, container: container(20) },
  },
  {
    id: 'crop-sayaendo',
    name: 'サヤエンドウ',
    nameReading: 'さやえんどう',
    family: 'マメ科',
    category: 'bean',
    defaultUnit: 'g',
    sourceIds: ['maff-sehi', 'nagano-kasai-ondo', 'takii-manual'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 4, endMonth: 5 },
      { region: 'cold', kind: 'harvest', startMonth: 6, endMonth: 7 },
      { region: 'temperate', kind: 'sow', startMonth: 10, endMonth: 11 },
      { region: 'temperate', kind: 'harvest', startMonth: 4, endMonth: 6 },
      { region: 'warm', kind: 'sow', startMonth: 10, endMonth: 11 },
      { region: 'warm', kind: 'harvest', startMonth: 3, endMonth: 5 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'full',
      wateringNote: '開花期に乾かさない。冬の間は控えめでよい。',
      wateringIntervalDays: 4,
      germinationDays: 7,
      transplantAfterDays: null,
      fertilizeAfterDays: 120,
      fertilizeIntervalDays: 20,
      harvestAfterDays: 170,
      harvestWindowDays: window(160, 190),
      harvestDurationDays: 40,
      temperature: temp([18, 20], [15, 20]),
      rotationYears: 4,
      tasks: [{ kind: 'stake', afterDays: 120, note: '春につるが伸び始めたらネットか支柱を' }],
      commonPests: ['うどんこ病', 'ハモグリバエ', 'アブラムシ'],
      tips: '花が咲いて 10 日ほどの若いさやを採る（絹さや）。スナップエンドウと同じ育て方。',
    },
    editorial: { beginner: true, container: container(25) },
  },
  {
    id: 'crop-soramame',
    name: 'ソラマメ',
    nameReading: 'そらまめ',
    family: 'マメ科',
    category: 'bean',
    defaultUnit: 'g',
    sourceIds: ['maff-sehi', 'takii-manual'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 4, endMonth: 4 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 8 },
      { region: 'temperate', kind: 'sow', startMonth: 10, endMonth: 11 },
      { region: 'temperate', kind: 'harvest', startMonth: 5, endMonth: 6 },
      { region: 'warm', kind: 'sow', startMonth: 10, endMonth: 11 },
      { region: 'warm', kind: 'harvest', startMonth: 4, endMonth: 5 },
    ],
    guide: {
      spacingCm: 40,
      sunlight: 'full',
      wateringNote: '発芽までと開花期に乾かさない。冬は控えめ。',
      wateringIntervalDays: 4,
      germinationDays: 10,
      transplantAfterDays: null,
      fertilizeAfterDays: 120,
      fertilizeIntervalDays: 30,
      harvestAfterDays: 190,
      harvestWindowDays: window(180, 210),
      harvestDurationDays: 20,
      temperature: temp([15, 20], [15, 20]),
      rotationYears: 4,
      tasks: [
        { kind: 'thin', afterDays: 130, note: '春に細い枝を抜いて 6〜7 本に整枝' },
        { kind: 'stake', afterDays: 130, note: '倒れないよう周りをひもで囲う' },
        { kind: 'pinch', afterDays: 160, note: '草丈 70cm で芯を止めるとアブラムシが減る' },
      ],
      commonPests: ['アブラムシ', '赤色斑点病', 'ハモグリバエ'],
      tips: '種はおはぐろ（黒い筋）を斜め下に向けて土に押し込む。さやが下を向いて背中が黒ずんだら収穫。',
    },
    editorial: { beginner: false, container: container(25) },
  },
  {
    id: 'crop-rakkasei',
    name: 'ラッカセイ',
    nameReading: 'らっかせい',
    family: 'マメ科',
    category: 'bean',
    defaultUnit: 'g',
    sourceIds: ['chiba-rakkasei', 'ja-hokkaido'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 5, endMonth: 6 },
      { region: 'temperate', kind: 'harvest', startMonth: 9, endMonth: 10 },
      { region: 'warm', kind: 'sow', startMonth: 4, endMonth: 6 },
      { region: 'warm', kind: 'harvest', startMonth: 9, endMonth: 11 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'full',
      wateringNote: '乾燥に強い。開花〜子房柄が土に潜る時期だけ乾かさない。',
      wateringIntervalDays: 5,
      germinationDays: 10,
      transplantAfterDays: null,
      fertilizeAfterDays: 40,
      fertilizeIntervalDays: null,
      harvestAfterDays: 130,
      harvestWindowDays: window(120, 150),
      harvestDurationDays: null,
      temperature: temp([25, 30], [20, 28]),
      rotationYears: 2,
      tasks: [
        { kind: 'net', afterDays: 1, note: '鳥に種を掘られるので発芽までかける' },
        { kind: 'hill', afterDays: 45, note: '開花が始まったら株元に。子房柄が潜りやすくなる' },
      ],
      commonPests: ['ハスモンヨトウ', 'コガネムシの幼虫', '褐斑病'],
      tips: '花が終わると子房柄が土に潜って実になる。開花から 80〜95 日が収穫の目安。葉が黄ばんだら試し掘り。',
    },
    editorial: { beginner: false, container: container(25) },
  },
  {
    id: 'crop-satoimo',
    name: 'サトイモ',
    nameReading: 'さといも',
    family: 'サトイモ科',
    category: 'tuber',
    defaultUnit: 'kg',
    sourceIds: ['saitama-satoimo', 'jeinou-satoimo', 'maff-akita-konsai'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 5, endMonth: 5 },
      { region: 'cold', kind: 'harvest', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'temperate', kind: 'harvest', startMonth: 10, endMonth: 11 },
      { region: 'warm', kind: 'plant', startMonth: 3, endMonth: 5 },
      { region: 'warm', kind: 'harvest', startMonth: 10, endMonth: 12 },
    ],
    guide: {
      spacingCm: 45,
      sunlight: 'full',
      wateringNote: '水を好む。夏の乾燥で芋が小さくなるので敷きわらと朝の水やりを。',
      wateringIntervalDays: 2,
      germinationDays: 30,
      transplantAfterDays: null,
      fertilizeAfterDays: 50,
      fertilizeIntervalDays: 30,
      harvestAfterDays: 180,
      harvestWindowDays: window(160, 200),
      harvestDurationDays: null,
      temperature: temp([25, 30], [25, 30]),
      rotationYears: 3,
      tasks: [
        { kind: 'hill', afterDays: 50, note: '発芽から 3 週間で 1 回目。追肥と一緒に' },
        { kind: 'hill', afterDays: 80, note: '2 回目。子芋が土から出ないように' },
      ],
      commonPests: ['ハスモンヨトウ', 'アブラムシ', 'セスジスズメの幼虫'],
      tips: '芽が出るまで 1 か月かかる。葉が黄ばみ始めたら試し掘りして大きさを確認する。',
    },
    editorial: { beginner: true, container: container(30) },
  },
  {
    id: 'crop-naganegi',
    name: '長ネギ',
    nameReading: 'ながねぎ',
    family: 'ヒガンバナ科',
    category: 'allium',
    defaultUnit: 'piece',
    sourceIds: ['maff-sehi', 'takii-manual'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 4, endMonth: 4 },
      { region: 'cold', kind: 'plant', startMonth: 6, endMonth: 7 },
      { region: 'cold', kind: 'harvest', startMonth: 10, endMonth: 11 },
      { region: 'temperate', kind: 'sow', startMonth: 3, endMonth: 4 },
      { region: 'temperate', kind: 'plant', startMonth: 6, endMonth: 7 },
      { region: 'temperate', kind: 'harvest', startMonth: 11, endMonth: 2 },
      { region: 'warm', kind: 'sow', startMonth: 3, endMonth: 4 },
      { region: 'warm', kind: 'plant', startMonth: 6, endMonth: 7 },
      { region: 'warm', kind: 'harvest', startMonth: 11, endMonth: 2 },
    ],
    guide: {
      spacingCm: 5,
      sunlight: 'full',
      wateringNote: '過湿を嫌う。植え付け後は乾いたときだけ。',
      wateringIntervalDays: 5,
      germinationDays: 10,
      transplantAfterDays: 80,
      fertilizeAfterDays: 30,
      fertilizeIntervalDays: 30,
      harvestAfterDays: 150,
      harvestWindowDays: window(130, 180),
      harvestDurationDays: 90,
      temperature: temp([15, 25], [15, 20]),
      rotationYears: 0,
      tasks: [
        { kind: 'hill', afterDays: 30, note: '追肥のたびに。白い部分を伸ばす' },
        { kind: 'hill', afterDays: 60 },
        { kind: 'hill', afterDays: 90, note: '葉の分かれ目まで埋めない' },
      ],
      commonPests: ['アブラムシ', 'さび病', 'ネギアザミウマ'],
      tips: '深さ 20cm 以上の溝に植え、追肥のたびに土を寄せる。寄せた分だけ白い部分が長くなる。',
    },
    editorial: { beginner: false, container: NO_CONTAINER },
  },
  {
    id: 'crop-nira',
    name: 'ニラ',
    nameReading: 'にら',
    family: 'ヒガンバナ科',
    category: 'allium',
    defaultUnit: 'bunch',
    perennial: true,
    sourceIds: ['ja-saitama-nira', 'jeinou-calendar'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 4, endMonth: 5 },
      { region: 'cold', kind: 'plant', startMonth: 6, endMonth: 7 },
      { region: 'cold', kind: 'harvest', startMonth: 5, endMonth: 9 },
      { region: 'temperate', kind: 'sow', startMonth: 3, endMonth: 4 },
      { region: 'temperate', kind: 'plant', startMonth: 6, endMonth: 7 },
      { region: 'temperate', kind: 'harvest', startMonth: 4, endMonth: 10 },
      { region: 'warm', kind: 'sow', startMonth: 3, endMonth: 4 },
      { region: 'warm', kind: 'plant', startMonth: 6, endMonth: 7 },
      { region: 'warm', kind: 'harvest', startMonth: 3, endMonth: 11 },
    ],
    guide: {
      spacingCm: 20,
      sunlight: 'full',
      wateringNote: '乾いたら。刈り取ったあとの追肥と水やりで次の葉が出る。',
      wateringIntervalDays: 3,
      germinationDays: 10,
      transplantAfterDays: 80,
      fertilizeAfterDays: 30,
      fertilizeIntervalDays: 30,
      harvestAfterDays: null,
      harvestWindowDays: null,
      harvestDurationDays: null,
      temperature: temp([20, 25], [20, 25]),
      rotationYears: 0,
      tasks: [],
      commonPests: ['アブラムシ', 'さび病', 'ネギアザミウマ'],
      tips: '1 年目は株を太らせて 2 年目から収穫。25cm に伸びたら地際 5cm で刈り、年に 3〜4 回採れる。3 年ごとに春先に株分け。',
    },
    editorial: { beginner: true, container: container(20) },
  },
  {
    id: 'crop-paseri',
    name: 'パセリ',
    nameReading: 'ぱせり',
    family: 'セリ科',
    category: 'herb',
    defaultUnit: 'bunch',
    sourceIds: ['kochi-paseri', 'jeinou-calendar'],
    calendars: [
      { region: 'cold', kind: 'sow', startMonth: 5, endMonth: 6 },
      { region: 'cold', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'temperate', kind: 'sow', startMonth: 4, endMonth: 5 },
      { region: 'temperate', kind: 'sow', startMonth: 9, endMonth: 10 },
      { region: 'temperate', kind: 'harvest', startMonth: 6, endMonth: 12 },
      { region: 'warm', kind: 'sow', startMonth: 3, endMonth: 5 },
      { region: 'warm', kind: 'sow', startMonth: 9, endMonth: 10 },
      { region: 'warm', kind: 'harvest', startMonth: 5, endMonth: 1 },
    ],
    guide: {
      spacingCm: 20,
      sunlight: 'partial',
      wateringNote: '乾燥に弱い。表面が乾いたらたっぷり。真夏は半日陰で。',
      wateringIntervalDays: 2,
      germinationDays: 14,
      transplantAfterDays: 40,
      fertilizeAfterDays: 30,
      fertilizeIntervalDays: 30,
      harvestAfterDays: 70,
      harvestWindowDays: window(60, 90),
      harvestDurationDays: 150,
      temperature: temp([15, 20], [15, 20]),
      rotationYears: 1,
      tasks: [{ kind: 'thin', afterDays: 25, note: '本葉 2〜3 枚で 1 本に' }],
      commonPests: ['キアゲハの幼虫', 'アブラムシ', 'ハダニ'],
      tips: '発芽に 2 週間かかる。種を一晩水につけるとそろう。外葉から摘み、常に 10 枚は残すと長く採れる。',
    },
    editorial: { beginner: false, container: container(15) },
  },
  {
    id: 'crop-myoga',
    name: 'ミョウガ',
    nameReading: 'みょうが',
    family: 'ショウガ科',
    category: 'tree',
    defaultUnit: 'piece',
    perennial: true,
    sourceIds: ['jeinou-myoga'],
    calendars: [
      { region: 'cold', kind: 'plant', startMonth: 4, endMonth: 5 },
      { region: 'cold', kind: 'harvest', startMonth: 8, endMonth: 9 },
      { region: 'temperate', kind: 'plant', startMonth: 3, endMonth: 4 },
      { region: 'temperate', kind: 'harvest', startMonth: 7, endMonth: 10 },
      { region: 'warm', kind: 'plant', startMonth: 3, endMonth: 4 },
      { region: 'warm', kind: 'harvest', startMonth: 7, endMonth: 10 },
    ],
    guide: {
      spacingCm: 30,
      sunlight: 'partial',
      wateringNote: '乾燥と直射日光を嫌う。夏は敷きわらをして乾いたらたっぷり。',
      wateringIntervalDays: 3,
      germinationDays: 40,
      transplantAfterDays: null,
      fertilizeAfterDays: 90,
      fertilizeIntervalDays: 60,
      harvestAfterDays: null,
      harvestWindowDays: null,
      harvestDurationDays: null,
      temperature: temp([20, 23], [20, 23]),
      rotationYears: 0,
      tasks: [],
      commonPests: ['ハスモンヨトウ', 'アブラムシ', '根茎腐敗病'],
      tips: '植えた年は 9 月から、翌年からは 7 月から採れる。花が開く前の固い花蕾を土の中から折り取る。4〜5 年で株分け。',
    },
    editorial: { beginner: true, container: container(25) },
  },
];
