/**
 * Android の自動バックアップ範囲を制御する config plugin。
 *
 * 背景: 生成される AndroidManifest は `android:allowBackup="true"` だけで
 * `fullBackupContent` / `dataExtractionRules` の指定が無く、**アプリデータ全体**が
 * クラウド自動バックアップの対象になっていた。写真は
 * `documentDirectory/garden-photos/` に貯まるので、増えるとクラウド側の容量上限に当たり、
 * **DB を含む全体が黙って対象外**になりうる。
 *
 * そこで対象を分ける:
 * - クラウド自動バックアップ = SQLite（DB）と設定のみ。栽培・作業ログ・収穫の
 *   テキストデータは確実に枠内へ収まり、常時 Google 側に保護される
 * - 端末間転送（D2D・容量上限なし）= 写真を含む全データ
 *
 * 写真のクラウド退避は、アプリ内の移行バックアップ（zip の共有）が担う。
 *
 * だいどこの `withDaidokoBackupRules`（#79 d①）と同じ立て付け。
 * さいえん手帳では写真ディレクトリ名が違うだけで、除外の考え方は同じ。
 *
 * 注意: ネイティブ設定なので、ローカルビルドへの反映には `--prebuild` が要る
 * （docs/リリース手順.md）。
 */
const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const BACKUP_RULES_FILE = 'saien_backup_rules.xml';
const DATA_EXTRACTION_RULES_FILE = 'saien_data_extraction_rules.xml';

// **SecureStore は必ず除外する。**
// expo-secure-store は自前の backup/dataExtraction ルールで
// `sharedpref` の `SecureStore` を cloud-backup・device-transfer の両方から外している。
// ところがマニフェストの `fullBackupContent` / `dataExtractionRules` は
// **1 つしか指定できず、後勝ちでこちらが上書きする**ので、こちらで同じ除外を
// 書かないと SecureStore の暗号文だけがバックアップに入る。
// 鍵は端末の Keystore にあって復元先には無いため、戻した値は復号できない。
// 現状 BYOK の導線は塞がっている（WBS 2.9b）が、v1.5 で開くと実害になる。
const EXCLUDE_SECURE_STORE = '  <exclude domain="sharedpref" path="SecureStore" />';

// API 30 以前（fullBackupContent）: クラウド自動バックアップは DB と設定に限る
const BACKUP_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- generated by plugins/withSaienBackupRules.js — 編集しない -->
<full-backup-content>
  <include domain="file" path="SQLite/" />
  <include domain="database" path="." />
  <include domain="sharedpref" path="." />
${EXCLUDE_SECURE_STORE}
</full-backup-content>
`;

// API 31+（dataExtractionRules）: クラウドは DB と設定のみ / 端末間転送は写真込み全部
const DATA_EXTRACTION_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- generated by plugins/withSaienBackupRules.js — 編集しない -->
<data-extraction-rules>
  <cloud-backup>
    <include domain="file" path="SQLite/" />
    <include domain="database" path="." />
    <include domain="sharedpref" path="." />
  ${EXCLUDE_SECURE_STORE}
  </cloud-backup>
  <device-transfer>
    <include domain="file" path="." />
    <include domain="database" path="." />
    <include domain="sharedpref" path="." />
  ${EXCLUDE_SECURE_STORE}
  </device-transfer>
</data-extraction-rules>
`;

function withBackupRuleResources(config) {
  return withDangerousMod(config, [
    'android',
    (modConfig) => {
      const xmlDir = path.join(
        modConfig.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, BACKUP_RULES_FILE), BACKUP_RULES_XML);
      fs.writeFileSync(path.join(xmlDir, DATA_EXTRACTION_RULES_FILE), DATA_EXTRACTION_RULES_XML);
      return modConfig;
    },
  ]);
}

function withBackupManifestAttributes(config) {
  return withAndroidManifest(config, (modConfig) => {
    const application = modConfig.modResults.manifest.application?.[0];
    if (!application) {
      throw new Error('withSaienBackupRules: AndroidManifest に application が見つかりません');
    }
    application.$['android:allowBackup'] = 'true';
    application.$['android:fullBackupContent'] = `@xml/${BACKUP_RULES_FILE.replace('.xml', '')}`;
    application.$['android:dataExtractionRules'] =
      `@xml/${DATA_EXTRACTION_RULES_FILE.replace('.xml', '')}`;
    return modConfig;
  });
}

module.exports = function withSaienBackupRules(config) {
  return withBackupManifestAttributes(withBackupRuleResources(config));
};
